# Generated by Django 2.2.4 on 2020-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_friend_list_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_list',
            name='isFriend',
            field=models.BooleanField(default=False),
        ),
    ]
