# Generated by Django 2.2.4 on 2020-11-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_friend_list_isfriend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_list',
            name='isFriend',
        ),
    ]
