# Generated by Django 2.2.4 on 2020-11-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_remove_friend_list_isfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
