# Generated by Django 3.0.7 on 2021-01-03 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0021_auto_20210102_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False, null=True, verbose_name='Likes')),
                ('comments', models.CharField(max_length=1000, null=True, verbose_name='Comments')),
                ('share_url', models.URLField(null=True, verbose_name='Share')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
