# Generated by Django 3.0.7 on 2021-01-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
