# Generated by Django 3.0.7 on 2021-01-18 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0025_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dated', models.DateTimeField(auto_now_add=True, verbose_name='Shared time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Post', verbose_name='Shared Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shared by')),
            ],
        ),
    ]
