# Generated by Django 3.0.7 on 2021-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_sharedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='create_dated',
            field=models.DateTimeField(verbose_name='Shared time'),
        ),
    ]
