# Generated by Django 3.0.7 on 2021-01-20 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0027_auto_20210119_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='sending_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to=settings.AUTH_USER_MODEL, verbose_name='Sending  user'),
        ),
    ]
