# Generated by Django 3.0.7 on 2021-01-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0028_friendrequest_sending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.Post', verbose_name='Shared Post'),
        ),
    ]
