# Generated by Django 3.0.7 on 2021-01-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_auto_20210121_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='create_dated',
            field=models.DateTimeField(null=True, verbose_name='Shared time'),
        ),
    ]
