# Generated by Django 3.0.7 on 2021-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_auto_20210128_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='first_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
