# Generated by Django 3.0.7 on 2021-01-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_auto_20210128_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_name',
        ),
    ]
