# Generated by Django 2.2.4 on 2020-10-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
